version: "3.8"

services:
  server:
    build:
      context: ./server
    image: mastermobo/vod:server-latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/voddb
      SPRING_DATASOURCE_USERNAME: voduser
      SPRING_DATASOURCE_PASSWORD: vodpass
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: voduser
      POSTGRES_PASSWORD: vodpass
      POSTGRES_DB: voddb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
