version: "3.8"

services:
  ci-docker-agent:
    build:
      context: .
    image: mastermobo/vod:ci-docker-agent-latest
    environment:
      DOCKER_HOST: tcp://0.0.0.0:2375
    user: root
    networks:
      - default
